### ISSUE TITLE
Crash on blu spell

### ISSUE THREAD

**Issue by GetAwayCoxn** [Spike2D/SimpleLog#1]
Sorry not a lot of context here, just downloaded your latest alpha, this SS is right after i zoned into SSR II for an alex farm. After talking to the pole etc, casted battery charge and blamo! All my settings etc are default with your addon. VERY excited about your project here, I'll try to duplicate and provide more details if needed.

![Igotudis_2022 06 21_134041](https://user-images.githubusercontent.com/66495755/174876198-e1a7e964-e8d3-4137-bcc9-5d263573e612.png)

**Comment by GetAwayCoxn** [comment]
Just saw your hotfix, and now I cannot duplicate, huzzah!

**Comment by Spike2D** [comment]
Glad it was related with that!
Let me know if you run into any other issue 👍
