### ISSUE TITLE
Null value crash

### ISSUE THREAD

**Issue by bangplaysgames** [Spike2D/SimpleLog#11]
Simplelog is sporadically having a null value on a table in lib\packethandlers.lua at line 363.  It's causing the addon to unload randomly.

**Comment by bangplaysgames** [comment]
![image](https://user-images.githubusercontent.com/69700079/200011637-17306ba1-29d1-419f-a5d3-d76c135ef9d9.png)

**Comment by bangplaysgames** [comment]
To add to this, there's another null value crash happening when attempting to concat the output strings.

When an player or mob hasn't rendered on the client, actor.owner_name and/or target.owner_name could have null values even though the table, itself isn't nil.

Proposed solution would be to init the tables prior to processing the packets so that you would have empty variables of appropriate types rather than null variables.

On the comedic side of suggestions, before concatenating the strings, you could test if the values of those are nil, and if so, set them to be "The Invisible Man".

**Comment by Spike2D** [comment]
Will lock this one up, keep #12 for discussion, same issue.
