### ISSUE TITLE
Event Callback Error

### ISSUE THREAD

**Issue by CRSD-Lau** [Spike2D/SimpleLog#12]
Packet Handler returning a nil value while trying to concatenate field "owner_name".

**Comment by Siushaga** [comment]
Seeing the same thing (private server).

stack traceback:
\addons\simplelog\lib\packethandlers.lua: in function 'HandleIncomingPacket'
\addons\simplelog\\simplelog.lua:61: in funciton <\addons\simplelog\\simplelog.lua:60>

**Comment by geekgirl101** [comment]
I can confirm this issue also, the issue takes place outside in areas where other players are engaging monsters.  This is the entire message I receive in the game:

Addon 'simple.log' encountered an error during an event callback 'packet_in'. Error: \addons\simplelog\lib\packethandlers.lua:293: attempt to concatenate field 'owner_name' (a nil value)
\addons\simplelog\lib\packethandlers.lua: in function 'HandleIncomingPacket'
\addons\simplelog\simplelog.lua:61 in function <\addons\simplelog\simplelog.lua:60>
Unloaded addon: simplelog

**Comment by Spike2D** [comment]
The crash has been addressed on 1.1 release, Debugging of IDs to see where the issue lies is needed, also if shared in this issue thread please specify if you're seeing it on Retail or P-Server

**Comment by Zaekkor** [comment]
Private Server (Horizon):
![image](https://user-images.githubusercontent.com/29270598/210903671-60f26c4d-9335-4c4a-a57a-9a02eb530d27.png)

**Comment by Zaekkor** [comment]
![image](https://user-images.githubusercontent.com/29270598/210906698-7654d93c-5c66-4dee-97b2-4f241fc56866.png)

Horizon

**Comment by geekgirl101** [comment]
This was on private servers.

**Comment by Zaekkor** [comment]
Happening when someone gets paralyzed and it blocks use of a spell or ability (on Horizon private server):

![image](https://user-images.githubusercontent.com/29270598/211090348-6e09f822-6b06-4b1a-b945-e628a1218c88.png)

**Comment by Spike2D** [comment]
Thanks for the info guys and gals, that should be all I needed 👍 will push for a solution now.

**Comment by Tarhish** [comment]
Could be a red herring, but I've noticed on three occasions that it crashed when a mob hit or was hit by a player that hadn't loaded in yet.  This is a very common situation when running around the map, but much less so when exping, and I rarely notice it when sitting still.
