### ISSUE TITLE
Style alters all other IMGUI addons.

### ISSUE THREAD

**Issue by ThornyFFXI** [Spike2D/SimpleLog#15]
Because SimpleLog calls StyleColorsDark, but does not reset it, all other addons will immediately take on the same styling.  Recommend using individual push/pop options or storing all original styles and restoring them at the end to avoid this problem.

**Comment by Spike2D** [comment]
Thanks Thorny, will push for a fix

**Comment by Spike2D** [comment]
StyleColorsDark removed.
