### ISSUE TITLE
Missing buff/debuff action descriptions

### ISSUE THREAD

**Issue by Brisk172** [Spike2D/SimpleLog#17]
Hello, not sure if this was intended, but when a monster uses an ability, for example "[Sand Beetle] Hi-Freq Field" there is no description of what that ability does.   For example, the battlemod addon for Windower would have "[Sand Beetle] Hi-Freq Field --> targets (Evasion Down).

Another example where it does not show damage after an ability, "[Desert Dhamel] Stomping", shows no damage to it's target after.  The battlemod addon for Windower would show "[Desert Dhamel] --> 100 hit target (Stomping).

**Comment by Spike2D** [comment]
Will look into it, can I have more info @Brisk172 was this on official servers, or a private one?

**Comment by Brisk172** [comment]
This was on a private server.  Here are some examples on Simple Log compared to no addon.  I didn't have time to get an example on battlelog.

Siege Bat - Ultrasonics (without Simple Log)
![Capture2](https://user-images.githubusercontent.com/126135255/221694654-14a87f7d-ccc3-4b2f-a526-88485b96c27a.PNG)

Siege Bat - Ultrasonics (with Simple Log)
![Capture2](https://user-images.githubusercontent.com/126135255/221694680-ec84a25d-ea76-4b00-b74c-4a72e442c43c.PNG)

Borer Beetle - Hi-Freq Field (without Simple Log)
![Capture2](https://user-images.githubusercontent.com/126135255/221697130-a1bb122e-d3a4-4bf6-a939-9fbe1c67b6fd.PNG)

Borer Beetle - Hi-Freq Field (with Simple Log)
![Capture2](https://user-images.githubusercontent.com/126135255/221697216-23fd545f-cf31-458b-8893-197dcaaf2c07.PNG)

Siege Bat - Blood Drain with no target specified (with Simple Log)
![Capture2](https://user-images.githubusercontent.com/126135255/221697352-5b2cc0d2-c6d3-4aa5-ae85-d65432694839.PNG)

Borer Beetle - Rhino Guard (without Simple Log)
![Capture8](https://user-images.githubusercontent.com/126135255/221697772-c2315d39-d849-46fe-8b17-51cd67cfbb44.PNG)


I also got a random error code that unloaded Simple Log:
![Capture_error](https://user-images.githubusercontent.com/126135255/221697858-c3828d82-e616-4768-9679-3f2b8991b053.PNG)
