### ISSUE TITLE
Crash while dismounting and attacking

### ISSUE THREAD

**Issue by zach2good** [Spike2D/SimpleLog#2]
Love this addon, amazing work!

Got a crash on `SimpleLog 0.5a (HOTFIX)`
- Running towards a Battering Ram while on a mount
- Target the ram
- Select attack to dismount and attack

![image](https://user-images.githubusercontent.com/1389729/174986478-6c1119cd-a9f2-42fe-a827-a39c340a7dd3.png)

**Comment by Spike2D** [comment]
Thanks for the report and kind words!
Would need a bit more info to boil it down, did you switch characters by any chance?
Will try to replicate.

**Comment by Spike2D** [comment]
Replicated, bugfix incoming 👍

**Comment by zach2good** [comment]
Nope, always the same character.

I'd log in, load the addon, get on my mount and go to find the placeholders
I was hunting for. Then I'd select attack while still mounted to get the
crash.
