### ISSUE TITLE
Mob TP moves have wrong ability names

### ISSUE THREAD

**Issue by WinterSolstice8** [Spike2D/SimpleLog#3]
![image](https://user-images.githubusercontent.com/60417494/175489074-148a4a0b-774e-4409-adcf-a96931055f9b.png)
![image](https://user-images.githubusercontent.com/60417494/175489215-dbdee4c0-4f88-4008-8283-2858316e2846.png)
![image](https://user-images.githubusercontent.com/60417494/175489671-a1578400-118f-4382-9414-eba07dba59d7.png)

I'm using the [0.7.1a release](https://github.com/Spike2D/SimpleLog/releases/tag/0.7.1a).

They look fine without simplelog being loaded, for what it's worth.

**Comment by Spike2D** [comment]
Thanks for the report, I know what's causing it, fix incoming along with some item message fixes.

**Comment by Spike2D** [comment]
Fixed on 0.8a, Thanks!
