### ISSUE TITLE
crashes from function SpellParse

### ISSUE THREAD

**Issue by GetAwayCoxn** [Spike2D/SimpleLog#4]
I have two SS for you, the first has little info unfortunately because it happened while i was just AFK in mhaura on a mule the other day. Wasn't even going to share but then got a second one from the same function but slightly different line reference just now so decided to share them both. Both of these happened before I updated to your lastest commit from yesterday but at first glance that fix doesn't seem related so again that's why I'm sharing here. First SS not much info to share as mentioned before other than it definitely was not directly after zoning in, second SS was on same system, different char, and I had just logged in and zoned out of the MH. I had taken no action except to target that login points moogle and got this error. There were other chars around me but unsure if they were taking any actions. Not sure what else would be relevant info for you/this, just hoping to help provide you what you need to work out the kinks. Loving it so far!

![Beane_2022 06 23_122738](https://user-images.githubusercontent.com/66495755/175570055-05525940-f223-4bb1-a96b-27512b1602f5.png)

![Wigmasterflex_2022 06 24_105725](https://user-images.githubusercontent.com/66495755/175570121-1386344d-07af-48cc-b432-d77019d640db.png)

**Comment by Spike2D** [comment]
Thanks for sharing it!
Both are related to the autoload issue which I believe should be ironed out on 14cac99 and eccb9bc 0.8a, I'll leave the issue open for now, will try to replicate however, which version was this on?

**Comment by GetAwayCoxn** [comment]
These both were definitely before .8a, was on .7.1a still, im updating to latest now and if i can replicate will report back here
