### ISSUE TITLE
Log spam while in Dyna-D

### ISSUE THREAD

**Issue by zach2good** [Spike2D/SimpleLog#5]
![image](https://user-images.githubusercontent.com/1389729/175782459-fa26dbee-c042-464e-8a2c-44a5e45ad31d.png)

Not sure of the cause, just while fighting regular mobs in Sandy Dyna-D

**Comment by zach2good** [comment]
For reference, I'm in a party of 4, there's another party of 4, and a full party of 6

**Comment by Spike2D** [comment]
That's a interesting one, will replicate and fix, thanks Zach!

**Comment by Spike2D** [comment]
@zach2good would you please share your chat_colors.lua settings on your config folder for the addon?

**Comment by zach2good** [comment]
config/addons/simplelog/<charname>/char_colors.lua:
```lua
--[[ 
* Colors are customizable based on party / alliance position. Use the colortest command to view the available colors.

* If you wish for a color to be unchanged from its normal color, set it to 0.
--]]

local colors = T{
	mob = 69,
	other = 8,
	
	p0 = 501,
	p1 = 204,
	p2 = 410,
	p3 = 492,
	p4 = 259,
	p5 = 260,
	
	al0 = 205,
	al1 = 359,
	al2 = 167,
	al3 = 038,
	al4 = 125,
	al5 = 185,
	
	a20 = 429,
	a21 = 257,
	a22 = 200,
	a23 = 481,
	a24 = 283,
	a25 = 208,
	
	mobdmg = 0,
	mydmg = 0,
	partydmg = 0,
	allydmg = 0,
	otherdmg = 0,
	
	spellcol = 0,
	mobspellcol = 0,
	abilcol = 0,
	wscol = 0,
	mobwscol = 0,
	statuscol = 0,
	enfeebcol = 501,
	itemcol = 256,
};

return colors;	
```

**Comment by Spike2D** [comment]
Got it, bug found, cheers mate!
Deploying fix in a few.
I'll add a note, but saving settings (even if no changes are done) will be required to fix the issue.
Sorry about that!
