### ISSUE TITLE
Incomplete "Player is no longer stunned" message

### ISSUE THREAD

**Issue by zach2good** [Spike2D/SimpleLog#7]
![image](https://user-images.githubusercontent.com/1389729/175830612-6b87ec27-85e8-4c2d-924f-01cfcfb33b26.png)

While fighting in the "One to be Feared" HTBF with 5x trusts -> incomplete message

**Comment by Spike2D** [comment]
Caused by a typo in;
https://github.com/Spike2D/SimpleLog/blob/065e40535605629778e317e8ef263466eb4d0c26/lib/packethandlers.lua#L182

Bug fixed, Thanks Zach
